on:
  workflow_dispatch:
    inputs:
      name:
        description: "Publish"
  release:
    types: [published]
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run build
      - run: sudo apt-get install ncftp
      - run: mv ./build ./www.winonaraiders.org
      - run: ncftpput -R -u ${{ secrets.FTP_USERNAME }} -p ${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }} . www.winonaraiders.org/
