on:
  release:
    types: [published]
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run build
      - run: sudo apt-get install git-ftp
      - run: git config git-ftp.url ${{ secrets.FTP_HOST }}
      - run: git config git-ftp.user ${{ secrets.FTP_USERNAME }}
      - run: git config git-ftp.password ${{ secrets.FTP_PASSWORD }}
      - run: git config git-ftp.syncroot build/
      - run: git ftp push
